[build]
  publish = "dist"
  command = "yarn build"

# 处理 SPA 路由，但排除静态文件
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/locales/*"
  to = "/locales/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 设置缓存头
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/locales/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/json"
